version: '3.0'

services:
  server:
    image: homeservice-server
    build: .
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    # environment:
    #   - DB_HOST=postgresdb
    #   - DB_USER=$POSTGRESDB_USER
    #   - DB_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
    #   - DB_NAME=$POSTGRESDB_DATABASE
    #   - DB_PORT=$POSTGRESDB_DOCKER_PORT
    volumes:
      - .:/src
    # depends_on:
    #   - postgres
    restart: unless-stopped
    networks:
      - homeservice
    command: npm run start:dev

  # postgres:
  #   build: ./src/db
  #   env_file:
  #     - .env
  #   environment:
  #     - POSTGRES_USER=$POSTGRESDB_USER
  #     - POSTGRES_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
  #     - POSTGRES_DB=$POSTGRESDB_DATABASE
  #   ports:
  #     - $POSTGRESDB_LOCAL_PORT:$POSTGRESDB_DOCKER_PORT
  #   volumes:
  #     - db:/var/lib/postgres
  #   restart: unless-stopped
  #   networks:
  #     - homeservice

networks:
  homeservice:
    name: homeservice
    driver: bridge

# volumes:
#   db:


